### ISSUE TITLE
Unable - pull the docker 

### ISSUE THREAD

**Issue by iamnaveenkumar** [pytorch/translate#190]
HI Team,

I am not pull Translate image from Docker. it is throwing error "unauthorized: authentication required".  Can you please help us on this?

Here is Log

> docker pull pytorch/translate

Using default tag: latest
latest: Pulling from pytorch/translate
297061f60c36: Pull complete 
e9ccef17b516: Pull complete 
dbc33716854d: Pull complete 
8fe36b178d25: Pull complete 
686596545a94: Pull complete 
f611dfbee954: Pull complete 
c51814f3e9ba: Pull complete 
5da0fc07e73a: Pull complete 
97462b1887aa: Extracting  64.06MB/477MB
924ea239f6fe: Downloading  469.4MB/585.2MB
f4a08faeb019: Download complete 
d2a2cd1e3b42: Download complete 
d714aef7a6eb: Download complete 
a525fe235307: Downloading  62.29MB/69.73MB
6657161af193: Downloading 
1839b2f91735: Waiting 
a6034776fbac: Waiting 
d1470d258ff1: Waiting 
cff0a26dca2d: Waiting 
4d6715d99c6a: Waiting 

> unauthorized: authentication required

**Comment by theweiho** [comment]
@soumith, @ezyang - is there some permission that needs to be opened up for https://hub.docker.com/r/pytorch/translate/ ?

**Comment by ezyang** [comment]
That's pretty weird. Sounds like a DockerHub permissions thing. I don't have access to the DockerHub.

**Comment by theweiho** [comment]
Closing since there's been no response. Please reopen if this is still an issue.
