### ISSUE TITLE
unexpected keyword argument 'max_tokens'

### ISSUE THREAD

**Issue by maxdel** [pytorch/translate#215]
I followed "Quickstart" section to install the framework.
When I run default training example (``bash pytorch_translate/examples/train_iwslt14.sh``) I get following error:

```
Traceback (most recent call last):
  File "pytorch_translate/train.py", line 974, in <module>
    main(args, single_process_main)
  File "pytorch_translate/train.py", line 945, in main
    return single_process_train(args)
  File "pytorch_translate/train.py", line 332, in single_process_main
    extra_state, trainer, task, epoch_itr = setup_training(args)
  File "pytorch_translate/train.py", line 285, in setup_training
    shard_id=args.distributed_rank,
TypeError: __init__() got an unexpected keyword argument 'max_tokens'

```

I am not quite sure what is exact problem here...
Please tell me if you need any additional information.

**Comment by theweiho** [comment]
Ah - sorry about that. This is due to divergence between the internal version of fairseq and the open-source version.

@myleott - the open-source version of EpochBatchIterator (https://github.com/pytorch/fairseq/blob/master/fairseq/data/iterators.py#L76) does not take max_tokens as a parameter, while the internal version does. Is there an open PR, or an expected timeline for syncing that change?

**Comment by sathishmtech01** [comment]
@theweiho Can you please share link or repo of the internal version of fairseq. Or is there any way to fix it..

**Comment by myleott** [comment]
It’s the public fairseq that’s ahead of the internal one. Please use an old fairseq commit for now. I believe this fairseq commit should work: 753935efe83513298cb7d5e2bf1995eda7b48817

We will be updating translate to work with the latest fairseq shortly.

**Comment by theweiho** [comment]
I think this should be resolved now that https://github.com/pytorch/translate/commit/a8bab8acda8e527d1eeac0f4d0a7244413408bdd has been committed? Please re-open if there are still issues!
