### ISSUE TITLE
train_with_tensorboard.py

### ISSUE THREAD

**Issue by tlysenko** [pytorch/translate#256]
Hi, there is no such file in your repo. Can you please add ?

**Comment by liezl200** [comment]
This was deleted in a recent refactor (https://github.com/pytorch/translate/commit/f93fac4e7046e310677bf84cece14cec623a2e22). We have decided not to support Tensorboard just yet. 

Feel free to modify the deleted file to be compatible with master and submit a pull request! You can add me as a reviewer.
