### ISSUE TITLE
Python version degrades

### ISSUE THREAD

**Issue by gvskalyan** [pytorch/translate#286]
while using this conda install -y -c caffe2 "pytorch-caffe2-cuda${TMP_CUDA_VERSION}.0-cudnn7"
![image](https://user-images.githubusercontent.com/42022935/50765248-56fa8400-129b-11e9-8b45-61a7e8e6c3bc.png) python version degrades to 2.7.15 and hence is not able to export model using https://github.com/pytorch/translate#exporting-a-model-with-onnx

Can this conversion be done on a CPU
Does pytorch1.0 does not need many of the above steps and facilitate the conversion process..

**Comment by liezl200** [comment]
export should be doable on CPU. Note that none of our ONNX tests require GPU: https://github.com/pytorch/translate/blob/master/pytorch_translate/test/test_onnx.py

whereas training DOES require GPU: https://github.com/pytorch/translate/blob/master/pytorch_translate/test/test_train.py

Tests which require GPU have this decorator `@unittest.skipIf(torch.cuda.device_count() < 1, "No GPU available for test.")`

**Comment by gvskalyan** [comment]
the build fails at make 2>&1 | tee MAKE_OUT
with the log ::

Scanning dependencies of target translation_decoder
[ 16%] Building CXX object CMakeFiles/translation_decoder.dir/Decoder.cpp.o
In file included from /home/local/usr/miniconda3/envs/pytrans/include/caffe2/core/logging.h:12:0,
                 from /home/local/usr/miniconda3/envs/pytrans/include/caffe2/core/init.h:6,
                 from /home/local/usr/translate/pytorch_translate/cpp/Decoder.cpp:32:
/home/local/usr/miniconda3/envs/pytrans/include/caffe2/proto/caffe2.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^

Please help @liezl200

**Comment by gvskalyan** [comment]
Is there average attention, shared embeddings, knowledge distillation under works as the Marian-NMT people do? @liezl200

**Comment by jhcross** [comment]
@gvskalyan, knowledge distillation is indeed in the works. Note also that shared embeddings are already an option for the transformer architecture [1]. We don't have immediate plans to add average attention, but we suggest looking at the hybrid architecture [2], which in the same spirit (faster inference for transformer models).


[1] https://github.com/pytorch/translate/blob/7752ad7f7c2118376f7d710cf729b355e0ffcb2b/pytorch_translate/transformer.py#L159-L171

[2] https://github.com/pytorch/translate/blob/7752ad7f7c2118376f7d710cf729b355e0ffcb2b/pytorch_translate/hybrid_transformer_rnn.py#L23

**Comment by gvskalyan** [comment]
I am still unable to make build due to the above error.

**Comment by FuKaiYin** [comment]
> I am still unable to make build due to the above error.

I had the same problem. Python 3.6 degrades to 2.7.

**Comment by gvskalyan** [comment]
@FuKaiYin You could try training the model in translate itself and use the docker image to export the model that might it!
