### ISSUE TITLE
Hybrid model performance

### ISSUE THREAD

**Issue by ManiaCello** [pytorch/translate#385]
Hello! I would like to ask if somebody have training results for the [hybrid model](https://github.com/pytorch/translate/blob/master/pytorch_translate/hybrid_transformer_rnn.py) implementation? Also please confirm, did i understand correctly that this model uses RNMT+ decoder, as in [Chen et al.](https://arxiv.org/abs/1804.09849) paper?

**Comment by jhcross** [comment]
Hi @ManiaCello, we don't have specific results to provide at this time, but anecdotally the architecture performs quite well, close to using a fully transformer model in many cases. You are correct that the decoder has essentially the same structure as Chen et al.
