### ISSUE TITLE
During Build Translate step i am getting this error, should i start all over again?

### ISSUE THREAD

**Issue by arsalan993** [pytorch/translate#41]
Btw this notice that caffe installed never failed but it got successfully ended at 18% . it was shocking to me but i let is go on .. 

Current error is below

`(base) test@dc-isb-ds-001:~/Downloads/translate/pytorch_translate/cpp/build$ cmake \
>   -DCMAKE_PREFIX_PATH="${CONDA_PATH}/usr/local" \
>   -DCMAKE_INSTALL_PREFIX="${CONDA_PATH}" .. \
>   2>&1 | tee CMAKE_OUT
CMake Error at CMakeLists.txt:8 (find_package):
  By not providing "FindCaffe2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Caffe2", but
  CMake did not find one.

  Could not find a package configuration file provided by "Caffe2" with any
  of the following names:

    Caffe2Config.cmake
    caffe2-config.cmake

  Add the installation prefix of "Caffe2" to CMAKE_PREFIX_PATH or set
  "Caffe2_DIR" to a directory containing one of the above files.  If "Caffe2"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/test/Downloads/translate/pytorch_translate/cpp/build/CMakeFiles/CMakeOutput.log".
`

**Comment by arsalan993** [comment]
Guys i rebuild every thing again so here is the exact error during install of caffe2 
after running this command `make install -j8 2>&1 | tee MAKE_OUT`
I get the following error at 18% : 

`nccl_static.a
[ 18%] No install step for 'nccl_external'
[ 18%] Completed 'nccl_external'
[ 18%] Built target nccl_external
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by jmp84** [comment]
@arsalan993, thanks for reporting the issue. Would you be able to give your configuration (linux distribution, gpu card, CUDA installation, etc.) and the full logs for all the steps (especially the step that fails)? In the meantime, feel free to use the AWS image.

**Comment by theweiho** [comment]
@arsalan993 - If you can share the full logs from MAKE_OUT and CMAKE_OUT, that'd be very helpful!

**Comment by arsalan993** [comment]
@jmp84  Intel CPU core i7 latest gen,  GPU : NVIDIA 1050 Ti, CUDA 8 , 
Guys despite the fact somehow i was able to install caffe2 from inside pytorch folder since they have setup.py file specially for caffe 2 therefore we dont have to build it .. but still i got the error which i have mentioned in 1st comment..

**Comment by jmp84** [comment]
@arsalan993, let us know if this fixes your installation, both build and the examples were retested successfully.
