### ISSUE TITLE
Do you include pre-trained translate model for popular languages ?

### ISSUE THREAD

**Issue by shishircc** [pytorch/translate#57]
Do you have any plans to include the pre-trained models for popular languages ?

**Comment by jmp84** [comment]
@shishircc, yes, we are planning to do that in the near future. Which languages are you interested in?

**Comment by shishircc** [comment]
@jmp84 our team is quite interested in Japanese, Chinese and Korean.

**Comment by shishircc** [comment]
@jmp84 do you have any rough guidance on when the pre-trained language translation models may be shared for asian languages such as above ?

**Comment by jmp84** [comment]
@shishircc, we're planning to start working on this in July.

**Comment by shishircc** [comment]
Thanks for letting us know

**Comment by jmp84** [comment]
Hi @shishircc, this is not high priority now, will let you know if it becomes so.
