### ISSUE TITLE
Are there any example of deep fusion?

### ISSUE THREAD

**Issue by sugiyamath** [pytorch/translate#646]
```class DeepFusionStrategy(MultiDecoderCombinationStrategy)``` seems that it's an implementation of deep fusion, but I'm not sure how to use it.

Could you please show me an example of deep fusion parameters exactly, like ```train_iwslt14.sh```?

**Comment by liezl200** [comment]
Unfortunately, deep fusion code is not maintained so we don't have parameters you can easily adapt
